export const items = [
  { name: "Ferroro Nutella Crepe", image: "/image/logo.webp", price: 16.0 },
  { name: "Pistachio Crepe", image: "/image/logo.webp", price: 16.0 },
  { name: "Dubia Chocolate Crepe", image: "/image/logo.webp", price: 18.0 },
  { name: "Blueberry Banana Crepe", image: "/image/logo.webp", price: 16.0 },
  {
    name: "Crème Brûlée Crepe (cone-style)",
    image: "/image/logo.webp",
    price: 16.0,
  },
  {
    name: "Nutella Strawberry Banana Crepe",
    image: "/image/logo.webp",
    price: 16.0,
  },
  { name: "Butter Mushroom Crepe", image: "/image/logo.webp", price: 15.0 },
  { name: "Beef Sausage Crepe", image: "/image/logo.webp", price: 16.0 },
  { name: "Salmon Crepe", image: "/image/logo.webp", price: 17.0 },
  { name: "Matcha Strawberry Crepe", image: "/image/logo.webp", price: 17.0 },
  {
    name: "Nutella Strawberry Banana Crepe (Featured)",
    image: "/image/logo.webp",
    price: 16.0,
  },
  { name: "Strawberry Matcha Latte", image: "/image/logo.webp", price: 8.5 },
  { name: "Hojicha Latte", image: "/image/logo.webp", price: 6.25 },
  {
    name: "Strawberry Banana Pineapple Smoothie",
    image: "/image/logo.webp",
    price: 8.5,
  },
  { name: "Banana Bread", image: "/image/logo.webp", price: 6.0 },
  { name: "Mango Hojicha Latte", image: "/image/logo.webp", price: 8.5 },
  { name: "Da Hong Pao Latte", image: "/image/logo.webp", price: 6.5 },
  { name: "Orange Espresso", image: "/image/logo.webp", price: 8.5 },
  { name: "White Mocha", image: "/image/logo.webp", price: 6.0 },
  { name: "Mocha", image: "/image/logo.webp", price: 6.0 },
  { name: "Latte", image: "/image/logo.webp", price: 5.5 },
  { name: "Cappuccino", image: "/image/logo.webp", price: 5.0 },
  { name: "Vanilla Latte", image: "/image/logo.webp", price: 5.5 },
  { name: "Espresso Shot", image: "/image/logo.webp", price: 2.0 },
  { name: "Pistachio Latte", image: "/image/logo.webp", price: 8.0 },
  { name: "Americano", image: "/image/logo.webp", price: 4.0 },
  { name: "Caramel Latte", image: "/image/logo.webp", price: 5.5 },
];
